import { expect, test } from "@playwright/test";

test.describe("Public API forms", () => {
  test("contact endpoint accepts a valid payload", async ({ request }) => {
    const email = `playwright-contact+${Date.now()}@example.com`;

    const response = await request.post("/api/contact", {
      headers: { "Content-Type": "application/json" },
      data: {
        name: "Playwright Tester",
        email,
        subject: "Automated contact form validation",
        message: "This is a test message generated by the Playwright suite.",
      },
    });

    expect(response.status(), "Successful submissions return 201").toBe(201);
    const payload = await response.json();
    expect(payload).toMatchObject({
      success: true,
      message: expect.stringContaining("Message sent"),
      id: expect.any(String),
    });
  });

  test("contact endpoint validates required fields", async ({ request }) => {
    const response = await request.post("/api/contact", {
      headers: { "Content-Type": "application/json" },
      data: {
        name: "",
        email: "invalid-email",
        subject: "Hi",
        message: "Short",
      },
    });

    expect(response.status(), "Invalid payload produces 400").toBe(400);
    const payload = await response.json();
    expect(payload).toMatchObject({
      error: "Invalid form data",
      details: expect.any(Array),
    });
  });
});

test.describe.serial("Newsletter subscription lifecycle", () => {
  const uniqueEmail = `playwright-newsletter+${Date.now()}@example.com`;

  test("subscribing to newsletter succeeds once", async ({ request }) => {
    const response = await request.post("/api/newsletter/subscribe", {
      headers: { "Content-Type": "application/json" },
      data: {
        email: uniqueEmail,
        source: "playwright-tests",
      },
    });

    expect(response.status()).toBe(201);
    const payload = await response.json();
    expect(payload).toMatchObject({
      success: true,
      message: expect.stringContaining("Successfully subscribed"),
      id: expect.any(String),
    });
  });

  test("subscribing with the same email is rejected", async ({ request }) => {
    const response = await request.post("/api/newsletter/subscribe", {
      headers: { "Content-Type": "application/json" },
      data: {
        email: uniqueEmail,
        source: "playwright-tests",
      },
    });

    expect(response.status()).toBe(409);
    const payload = await response.json();
    expect(payload).toMatchObject({
      error: "Email already subscribed",
    });
  });

  test("unsubscribing removes active subscriber", async ({ request }) => {
    const response = await request.post("/api/newsletter/unsubscribe", {
      headers: { "Content-Type": "application/json" },
      data: {
        email: uniqueEmail,
      },
    });

    expect(response.status()).toBe(200);
    const payload = await response.json();
    expect(payload).toMatchObject({
      success: true,
      message: expect.stringContaining("Successfully unsubscribed"),
    });
  });

  test("unsubscribing again returns not found", async ({ request }) => {
    const response = await request.post("/api/newsletter/unsubscribe", {
      headers: { "Content-Type": "application/json" },
      data: {
        email: uniqueEmail,
      },
    });

    expect(response.status()).toBe(404);
    const payload = await response.json();
    expect(payload).toMatchObject({
      error: "Email not found",
    });
  });
});
